/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check health of all services.
         *
         *     Returns:
         *         Service health status
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query
         * @description Query the knowledge base using RAG.
         *
         *     Args:
         *         request: Query request with question and parameters
         *         pipeline: RAG pipeline instance (injected)
         *
         *     Returns:
         *         Answer with retrieved chunks and optional concept graph
         */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Pdfs
         * @description Ingest PDF documents into the knowledge base.
         *
         *     Args:
         *         request: Ingestion request with file paths
         *         neo4j: Neo4j client (injected)
         *         embeddings: Embedding service (injected)
         *
         *     Returns:
         *         Ingestion results and statistics
         */
        post: operations["ingest_pdfs_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/{concept}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Concept Graph
         * @description Get the knowledge graph neighborhood around a concept.
         *
         *     Args:
         *         concept: Central concept name
         *         depth: How many relationship hops to traverse (1-4)
         *         neo4j: Neo4j client (injected)
         *
         *     Returns:
         *         Graph structure with nodes and edges
         */
        get: operations["get_concept_graph_graph__concept__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChunkMetadata
         * @description Metadata for a document chunk.
         */
        ChunkMetadata: {
            /** Chunk Id */
            chunk_id: string;
            /** Course */
            course?: string | null;
            /** Lecture */
            lecture?: string | null;
            /** Topic */
            topic?: string | null;
            /** Page Num */
            page_num?: number | null;
            /** Relevance Score */
            relevance_score?: number | null;
        };
        /**
         * Citation
         * @description Quoted span extracted from a retrieved chunk.
         */
        Citation: {
            /** Chunk Id */
            chunk_id: string;
            /** Quote */
            quote: string;
        };
        /**
         * ConceptEdge
         * @description Graph edge between concepts.
         */
        ConceptEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Edge Type */
            edge_type: string;
            /** Weight */
            weight?: number | null;
        };
        /**
         * ConceptGraph
         * @description Knowledge graph structure.
         */
        ConceptGraph: {
            /** Nodes */
            nodes: components["schemas"]["ConceptNode"][];
            /** Edges */
            edges: components["schemas"]["ConceptEdge"][];
        };
        /**
         * ConceptNode
         * @description Graph concept node.
         */
        ConceptNode: {
            /** Name */
            name: string;
            /** Node Type */
            node_type: string;
            /** Description */
            description?: string | null;
        };
        /**
         * DocumentChunk
         * @description Retrieved document chunk with metadata.
         */
        DocumentChunk: {
            /** Content */
            content: string;
            metadata: components["schemas"]["ChunkMetadata"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Neo4J Connected */
            neo4j_connected: boolean;
            /** Redis Connected */
            redis_connected: boolean;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * IngestRequest
         * @description Request to ingest PDF documents.
         */
        IngestRequest: {
            /**
             * File Paths
             * @description Paths to PDF files
             */
            file_paths: string[];
            /**
             * Course Name
             * @description Course name override
             */
            course_name?: string | null;
            /**
             * Overwrite
             * @description Overwrite existing chunks
             * @default false
             */
            overwrite: boolean;
        };
        /**
         * IngestResponse
         * @description Response from PDF ingestion.
         */
        IngestResponse: {
            /** Files Processed */
            files_processed: number;
            /** Chunks Created */
            chunks_created: number;
            /** Concepts Extracted */
            concepts_extracted: number;
            /** Processing Time Ms */
            processing_time_ms: number;
            /** Errors */
            errors?: string[];
        };
        /**
         * QueryRequest
         * @description Request model for RAG query endpoint.
         */
        QueryRequest: {
            /**
             * Question
             * @description User question
             */
            question: string;
            /**
             * Max Chunks
             * @description Maximum chunks to return
             * @default 5
             */
            max_chunks: number;
            /**
             * Include Graph
             * @description Include concept graph in response
             * @default true
             */
            include_graph: boolean;
        };
        /**
         * QueryResponse
         * @description Response model for RAG query endpoint.
         */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** Chunks */
            chunks: components["schemas"]["DocumentChunk"][];
            graph?: components["schemas"]["ConceptGraph"] | null;
            /** Processing Time Ms */
            processing_time_ms: number;
            /** Cost Cents */
            cost_cents: number;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_pdfs_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_concept_graph_graph__concept__get: {
        parameters: {
            query?: {
                /** @description Graph traversal depth */
                depth?: number;
            };
            header?: never;
            path: {
                concept: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
